### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by eatgreenjiao** [924973292/MambaPro#1]
您好，您的ReadMe文件中提到的论文链接指向的是您的另一篇TOP-reid的论文链接，可以修改一下吗

**Comment by 924973292** [comment]
Thank you for the reminder. The paper has not been officially published yet and is expected to be submitted to ArXiv this week or next. The link will be updated accordingly.

**Comment by 924973292** [comment]
Our paper is on ArXiv now: [Paper](https://arxiv.org/pdf/2412.10707)

**Comment by eatgreenjiao** [comment]
> Our paper is on ArXiv now: [Paper](https://arxiv.org/pdf/2412.10707)

Thanks！
