### ISSUE TITLE
Question about  decoder

### ISSUE THREAD

**Issue by eatgreenjiao** [924973292/MambaPro#3]
Hello, thank you very much for your excellent work. May I ask if you have tried replacing the transformer layer with a mamba layer in the encoding stage, that is, how does it work when mamba is used as the encoder?

**Comment by 924973292** [comment]
Thank you for your attention.

1. Replacing the traditional Transformer backbone with Vmamba did not improve training efficiency, and often increased memory usage, causing slower training. During testing, although the Flops are lower, the metrics still lag behind the Transformer. Additionally, the performance difference is not significant on small datasets, but Vmamba's backbone leads to poor performance on large-scale datasets.

2. You can mimic the truncation operation from MambaReID to improve feature resolution and thereby enhance results.

3. Currently, directly migrating to the encoder layer may require special adjustments to adapt to the ReID task. Moreover, I have not tried modules with mamba2 components, which might yield better results.

**Comment by eatgreenjiao** [comment]
Thank you for your generous help, I understand, thank you！
